### PR TITLE
Add appveyor CI config

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/metanorma/metanorma/issues/41

### CODE REVIEW

**Comment by CAMOBAP795** [comment]
@ronaldtse tests failed because  HTTP 400 for http://www.std.gov.cn/search/stdPage
 
```
type Status report
message Required String parameter 'q' is not present
description The request sent by the client was syntactically incorrect.
```

Is it possible to use some local file instead of remote?

**Comment by opoudjis** [comment]
I'll leave this pull review open. Changing the test files to use a local counterpart would be a task for @andrew2net; @ronaldtse, should he go ahead and do so?

**Comment by ronaldtse** [comment]
@andrew2net can you help fix the test? I think the gem needs to be fixed.

**Comment by andrew2net** [comment]
@ronaldtse ok, I'll check tests

**Comment by opoudjis** [comment]
The errors now are UTF-8 errors: the Windows version is treating the raw UTF-8 as bytes. I've had to inject

````
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8
````

into the Gemfile to get @andrew2net's specs to work. Presumably @CAMOBAP795 you will have to either do something like that, or make the spec code more overt about UTF-8.

**Comment by andrew2net** [comment]
@opoudjis looks like it was some issue on the server side when I run tests, so I got an encoding error with `File.write`. I added encoding: 'utf-8' to `File.write` as we did on other gems.

**Comment by opoudjis** [comment]
@andrew2net I don't think you've pushed this change yet.

**Comment by andrew2net** [comment]
@opoudjis here all the changes https://github.com/metanorma/gbbib/pull/18/commits/47fbd7f240cccf87c15f673fabcf4e94d2e8e495

**Pull request merged**
